### ISSUE TITLE
Failed to build on Windows in GitHub Actions.

### ISSUE THREAD

**Issue by chaoticlonghair** [nervosnetwork/ckb-vm#417]
**Describe the bug**

Failed to build on Windows in GitHub Actions.

Error messages:

```
  --- stderr
  thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ckb-vm-0.24.6\build.rs:51:17:
  Command["yasm" "-p" "gas" "-f" "x64" "-m" "amd64" "REPO_PATH\\target\\debug\\build\\ckb-vm-e4c77d8be0c21cb5\\out\\execute_x64-expanded.S" "-o" "REPO_PATH\\target\\debug\\build\\ckb-vm-e4c77d8be0c21cb5\\out\\execute_x64.o"] exits with non-success status: ExitStatus(ExitStatus(3221225781))
```

I know there is a new release (`0.24.9`), but:
- I didn't find a fix for this issue in the change log.
- I couldn't set the version, because it was introduced through dependencies (`ckb-testtool`). 

p.s. I tried 3 times to make sure it's a deterministic failure.

**Environment**
 - OS: `windows-latest` in GitHub Actions
 - Version: `ckb-vm v0.24.6`
 - Rust Toolchain: `1.76.0`
 - LLVM installation commands:
   ```yaml
      - name: Install LLVM on Windows                                                                                    
        if: matrix.os == 'windows-latest'                                                                                
        shell: pwsh                                                                                                      
        run: |                                                                                                           
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"                                                                      
          scoop install llvm yasm                                                                                        
          echo "$env:USERPROFILE\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append  
   ```
